### ISSUE TITLE
Improper HTTP request handling

### ISSUE THREAD

**Issue by dedd4** [OpenManifest/openmanifest#164]
**Describe the bug**
The current online build of OpenManifest (openmanifest.org) is mis-handling HTTP requests, in the form of dropping the first "/" character.

**To Reproduce**
1. Request Openmanifest.org (Confirm webserver is up) (Returns openamnifest.org/login)
2. Request Openmanifest.org/login (Incorrectly handled request) (Returns openmanifest.orglogin/)
3. Request Openmanifest.org/login/test (Incorrectly handled request) (Returns openmanifest.orglogin/test/)

Implication of the above behaviour, is that users cannot follow hyperlinks sent to their email.

Example:
- https://www.openmanifest.org/users/confirmation?confirmation_token=AAAAAAAAAAAAA
- https://www.openmanifest.org/change-password?token=AAAAAAAAAAAA

Recreated on:
Brave ([Version 1.51.114 Chromium: 113.0.5672.92 (Official Build) (64-bit)](https://brave.com/latest/))
Firefox (113.0.1 (64-bit))

Not sure if this issue is caused by the project, or the infrastructure hosting openmanifest.org.

**Comment by Amnesthesia** [comment]
Hiya

Thanks for the bug report! A fix for this is being deployed :)
